### ISSUE TITLE
large menubar gap

### ISSUE THREAD

**Issue by scottjl** [castdrian/ishare#26]
ran ishare, it created a huge (3 icon wide i'd guess) gap between itself and the next icon to the left of it. i could click on the app icon and it functioned as expected, if i clicked on the gap it dropped down a 1 line blank menu.

quitting ishare made the gap menu go away. relaunching app brings it back.

**Comment by castdrian** [comment]
that is most likely related to the placeholder that is being created for the stop recording button in the app delegate, I haven't encountered this before since it always is the leftmost item for me, will rewrite the logic for the recording parts in the app delegate to resolve this, thanks for notifying
